<a href="https://colab.research.google.com/github/joohoshin/MLDL_Basic/blob/master/12_2_company_clustering_with_kmeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

def get_fin(stock_code):
  raw = pd.read_html('https://finance.naver.com/item/main.nhn?code={}'.format(stock_code),attrs={'class':'tb_type1 tb_num tb_type1_ifrs'},encoding='cp949')
  fin_df = raw[0]
  fin_df.columns= fin_df.columns.get_level_values(1)
  fin_df = fin_df.set_index('주요재무정보')
  df = fin_df.iloc[:,8]
  df= fin_df.iloc[:,8]
  df.loc['종목코드']=stock_code
  return df

In [ ]:
get_fin('005930')

주요재무정보
매출액          529661
영업이익          81463
당기순이익         55551
영업이익률         15.38
순이익률          10.49
ROE(지배주주)      8.49
부채비율          32.67
당좌비율         250.04
유보율           29478
EPS(원)          808
PER(배)        16.52
BPS(원)        38534
PBR(배)         1.37
주당배당금(원)        NaN
시가배당률(%)        NaN
배당성향(%)         NaN
종목코드         005930
Name: 2020.06, dtype: object

In [ ]:
def get_fins(stock_codes):
  res=[]
  for stock_code in stock_codes:
    print(stock_code)
    df= get_fin(stock_code)
    res.append(df)
  res_df = pd.concat(res, axis=1)
  return res_df

In [ ]:
stock_codes = ['005930','000660']

In [ ]:
get_fins(stock_codes)

005930
000660

          2020.06  2020.06
주요재무정보
매출액        529661    86065
영업이익        81463    19467
당기순이익       55551    12643
영업이익률       15.38    22.62
순이익률        10.49    14.69
ROE(지배주주)    8.49     4.71
부채비율        32.67    40.19
당좌비율       250.04   110.41
유보율         29478  1320.31
EPS(원)        808     1735
PER(배)      16.52     27.1
BPS(원)      38534    72197
PBR(배)       1.37     1.18
주당배당금(원)      NaN      NaN
시가배당률(%)      NaN      NaN
배당성향(%)       NaN      NaN
종목코드       005930   000660

In [ ]:
df= get_fins(stock_codes)

005930
000660

In [ ]:
df.columns = df.loc['종목코드',:]

In [ ]:
df= df.drop('종목코드')

In [ ]:
df

종목코드       005930   000660
주요재무정보
매출액        529661    86065
영업이익        81463    19467
당기순이익       55551    12643
영업이익률       15.38    22.62
순이익률        10.49    14.69
ROE(지배주주)    8.49     4.71
부채비율        32.67    40.19
당좌비율       250.04   110.41
유보율         29478  1320.31
EPS(원)        808     1735
PER(배)      16.52     27.1
BPS(원)      38534    72197
PBR(배)       1.37     1.18
주당배당금(원)      NaN      NaN
시가배당률(%)      NaN      NaN
배당성향(%)       NaN      NaN

상장법인 코드 받기

https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage

In [ ]:
stock_codes = pd.read_excel('/content/drive/My Drive/ML_DL_202002/상장법인목록.xlsx')

In [ ]:
stock_codes

            회사명    종목코드  ...                          홈페이지     지역
0           빅히트  352820  ...     http://www.bighitcorp.com  서울특별시
1           넥스틴  348210  ...          http://nextinsol.com    경기도
2          원방테크   53080  ...        http://wonbangtech.com   충청북도
3           비나텍  126340  ...         http://www.vina.co.kr   전라북도
4     엔에이치스팩17호  359090  ...                           NaN  서울특별시
...         ...     ...  ...                           ...    ...
2376     CJ대한통운     120  ...    http://www.cjlogistics.com  서울특별시
2377      메리츠화재      60  ...     http://www.meritzfire.com  서울특별시
2378         경방      50  ...    http://www.kyungbang.co.kr  서울특별시
2379      유수홀딩스     700  ...  http://www.eusu-holdings.com  서울특별시
2380   한진중공업홀딩스    3480  ...  http://www.hhic-holdings.com    경기도

[2381 rows x 9 columns]

In [ ]:
comp_df = pd.read_excel('/content/drive/My Drive/ML_DL_202002/상장법인목록.xlsx', converters={'종목코드':str})

In [ ]:
comp_df

            회사명    종목코드  ...                          홈페이지     지역
0           빅히트  352820  ...     http://www.bighitcorp.com  서울특별시
1           넥스틴  348210  ...          http://nextinsol.com    경기도
2          원방테크  053080  ...        http://wonbangtech.com   충청북도
3           비나텍  126340  ...         http://www.vina.co.kr   전라북도
4     엔에이치스팩17호  359090  ...                           NaN  서울특별시
...         ...     ...  ...                           ...    ...
2376     CJ대한통운  000120  ...    http://www.cjlogistics.com  서울특별시
2377      메리츠화재  000060  ...     http://www.meritzfire.com  서울특별시
2378         경방  000050  ...    http://www.kyungbang.co.kr  서울특별시
2379      유수홀딩스  000700  ...  http://www.eusu-holdings.com  서울특별시
2380   한진중공업홀딩스  003480  ...  http://www.hhic-holdings.com    경기도

[2381 rows x 9 columns]

In [ ]:
stock_codes = comp_df.종목코드

In [ ]:
stock_codes

0       352820
1       348210
2       053080
3       126340
4       359090
         ...
2376    000120
2377    000060
2378    000050
2379    000700
2380    003480
Name: 종목코드, Length: 2381, dtype: object

In [ ]:
#raw_df = get_fins(stock_codes[:50]) # 일부 데이터는 들어오는 값에 따라서 에러 발생

352820
348210
053080
126340
359090

IndexError: ignored

In [ ]:
#get_fin('359090')

https://finance.naver.com/item/main.nhn?code=359090
스팩이라는 특수 종류로 재무데이터가 없음

In [ ]:
def get_fins2(stock_codes):
  res=[]
  
  for stock_code in stock_codes:
    try:   # 예외처리
      df= get_fin(stock_code)
      res.append(df)
      print(stock_code)
    except:
      print(stock_code,": 에러로 제외")
  res_df = pd.concat(res, axis=1)
  res_df.columns = res_df.loc['종목코드',:]
  res_df= res_df.drop('종목코드')
  return res_df

In [ ]:
stock_codes=stock_codes.sort_values()

In [ ]:
raw_df = get_fins2(stock_codes[:50])

000020
000040
000050
000060
000070
000080
000100
000120
000140
000150
000180
000210
000220
000230
000240
000250
000270
000300
000320
000370
000390
000400
000430
000440
000480
000490
000500
000520
000540
000590
000640
000650
000660
000670
000680
000700
000720
000760
000810
000850
000860
000880
000890
000910
000950
000970
000990
001000
001020
001040

In [ ]:
raw_df

종목코드        000020  000040   000050   000060  ...  000990  001000   001020   001040
주요재무정보                                        ...
매출액            698     312      862    27111  ...    2417       9     2024    77940
영업이익            62       8       33     1462  ...     771      -5      132     3588
당기순이익           67      -2       56     1062  ...     504      -4       64      552
영업이익률         8.91    2.42     3.88     5.39  ...   31.89  -55.61      6.5      4.6
순이익률          9.62   -0.49     6.48     3.92  ...   20.84  -44.89     3.14     0.71
ROE(지배주주)     5.67  -74.95      5.6    13.27  ...   24.51    0.82    -3.48     4.03
부채비율         24.78  171.79    96.53    852.4  ...   52.24  127.72  1931.85   171.37
당좌비율        386.09   55.08    34.89      NaN  ...  108.74    8.71    40.58       53
유보율        1000.55  -19.74  5408.12  4560.77  ...  266.83  487.91  -156.84  2606.13
EPS(원)         241      -7      204      938  ...    1131     -17      181      770
PER(배)       26.44   -1.09      8.2     4.09  ...     7.9   501.9   -46.38    16.77
BPS(원)       11272     459    28327    23329  ...   16924     588      767   141320
PBR(배)        1.44    1.45     0.43     0.54  ...     1.7     4.1     1.52     0.61
주당배당금(원)       NaN     NaN      NaN      NaN  ...     NaN     NaN      NaN      NaN
시가배당률(%)       NaN     NaN      NaN      NaN  ...     NaN     NaN      NaN      NaN
배당성향(%)        NaN     NaN      NaN      NaN  ...     NaN     NaN      NaN      NaN

[16 rows x 50 columns]

In [ ]:
df=raw_df.T

In [ ]:
df

주요재무정보     매출액   영업이익  당기순이익  영업이익률  ... PBR(배) 주당배당금(원) 시가배당률(%) 배당성향(%)
종목코드                                 ...
000020     698     62     67   8.91  ...   1.44      NaN      NaN     NaN
000040     312      8     -2   2.42  ...   1.45      NaN      NaN     NaN
000050     862     33     56   3.88  ...   0.43      NaN      NaN     NaN
000060   27111   1462   1062   5.39  ...   0.54      NaN      NaN     NaN
000070    5795    337    281   5.82  ...   0.31      NaN      NaN     NaN
000080    5816    541    349    9.3  ...   2.88      NaN      NaN     NaN
000100    4155    357    343   8.58  ...   1.76      NaN      NaN     NaN
000120   26500    839    362   3.16  ...   0.94      NaN      NaN     NaN
000140    5797    575    369   9.92  ...   1.03      NaN      NaN     NaN
000150   42092     79  -2372   0.19  ...   0.43      NaN      NaN     NaN
000180     423     16     17   3.81  ...   0.18      NaN      NaN     NaN
000210   25477   3071   1885  12.05  ...   0.51      NaN      NaN     NaN
000220     247     17     -7   6.76  ...   1.08      NaN      NaN     NaN
000230    1473     99     59   6.72  ...   0.77      NaN      NaN     NaN
000240    1757     99    130   5.63  ...   0.36      NaN      NaN     NaN
000250     443     37     44   8.29  ...   4.91      NaN      NaN     NaN
000270  113688   1452   1263   1.28  ...   0.44      NaN      NaN     NaN
000300    1072     39   -201   3.67  ...   0.76      NaN      NaN     NaN
000320    2197     87     48   3.97  ...   0.26      NaN      NaN     NaN
000370   19393    388    281      2  ...   0.16      NaN      NaN     NaN
000390    1438     57     40   3.94  ...   0.38      NaN      NaN     NaN
000400    9114    350    247   3.84  ...   0.49      NaN      NaN     NaN
000430    1658   -121    -82  -7.32  ...   0.41      NaN      NaN     NaN
000440     127      2      2   1.94  ...   0.92      NaN      NaN     NaN
000480    1592    -18    350  -1.15  ...   0.38      NaN      NaN     NaN
000490    2569    265    185  10.31  ...   0.38      NaN      NaN     NaN
000500    2399     54     56   2.24  ...   0.24      NaN      NaN     NaN
000520     294     21      3   7.25  ...   1.82      NaN      NaN     NaN
000540   10718    237    198   2.21  ...    0.2      NaN      NaN     NaN
000590     343     52     38  15.08  ...    0.3      NaN      NaN     NaN
000640    2003    142     64   7.09  ...   0.77      NaN      NaN     NaN
000650      71    -19     -2 -26.74  ...   1.87      NaN      NaN     NaN
000660   86065  19467  12643  22.62  ...   1.18      NaN      NaN     NaN
000670    7139    122    304    1.7  ...   0.24      NaN      NaN     NaN
000680     904    -39     72  -4.29  ...    0.3      NaN      NaN     NaN
000700     779      2     53   0.22  ...   0.65      NaN      NaN     NaN
000720   45442   1539    694   3.39  ...   0.55      NaN      NaN     NaN
000760     110      1     -8   1.26  ...    0.4      NaN      NaN     NaN
000810   61159   3858   2763   6.31  ...   0.51      NaN      NaN     NaN
000850     418      6     41   1.33  ...   0.23      NaN      NaN     NaN
000860     826     28     75   3.39  ...   0.17      NaN      NaN     NaN
000880  110041   5013   3507   4.56  ...   0.43      NaN      NaN     NaN
000890     196      8      -   4.01  ...   1.19      NaN      NaN     NaN
000910     434     22     10   5.18  ...   0.94      NaN      NaN     NaN
000950     244    -42    -45 -17.21  ...    0.3      NaN      NaN     NaN
000970    1128     25     21   2.24  ...    0.7      NaN      NaN     NaN
000990    2417    771    504  31.89  ...    1.7      NaN      NaN     NaN
001000       9     -5     -4 -55.61  ...    4.1      NaN      NaN     NaN
001020    2024    132     64    6.5  ...   1.52      NaN      NaN     NaN
001040   77940   3588    552    4.6  ...   0.61      NaN      NaN     NaN

[50 rows x 16 columns]

In [ ]:
df = pd.merge(df, comp_df[['종목코드', '회사명', '업종']], how='left', on=['종목코드'])

In [ ]:
df

      종목코드     매출액   영업이익  ... 배당성향(%)        회사명                        업종
0   000020     698     62  ...     NaN       동화약품                   의약품 제조업
1   000040     312      8  ...     NaN      KR모터스            그외 기타 운송장비 제조업
2   000050     862     33  ...     NaN         경방                    종합 소매업
3   000060   27111   1462  ...     NaN      메리츠화재                       보험업
4   000070    5795    337  ...     NaN      삼양홀딩스                    기타 금융업
5   000080    5816    541  ...     NaN      하이트진로                 알코올음료 제조업
6   000100    4155    357  ...     NaN       유한양행                   의약품 제조업
7   000120   26500    839  ...     NaN     CJ대한통운                 도로 화물 운송업
8   000140    5797    575  ...     NaN   하이트진로홀딩스                    기타 금융업
9   000150   42092     79  ...     NaN         두산       회사 본부 및 경영 컨설팅 서비스업
10  000180     423     16  ...     NaN     성창기업지주       회사 본부 및 경영 컨설팅 서비스업
11  000210   25477   3071  ...     NaN       대림산업                    토목 건설업
12  000220     247     17  ...     NaN       유유제약                   의약품 제조업
13  000230    1473     99  ...     NaN      일동홀딩스                   의약품 제조업
14  000240    1757     99  ...     NaN  한국테크놀로지그룹                    기타 금융업
15  000250     443     37  ...     NaN      삼천당제약                   의약품 제조업
16  000270  113688   1452  ...     NaN      기아자동차         자동차용 엔진 및 자동차 제조업
17  000300    1072     39  ...     NaN      대유플러스            통신 및 방송 장비 제조업
18  000320    2197     87  ...     NaN      노루홀딩스                    기타 금융업
19  000370   19393    388  ...     NaN     한화손해보험                       보험업
20  000390    1438     57  ...     NaN    삼화페인트공업               기타 화학제품 제조업
21  000400    9114    350  ...     NaN     롯데손해보험                       보험업
22  000430    1658   -121  ...     NaN       대원강업             자동차 신품 부품 제조업
23  000440     127      2  ...     NaN     중앙에너비스                 기타 전문 도매업
24  000480    1592    -18  ...     NaN       조선내화          내화, 비내화 요업제품 제조업
25  000490    2569    265  ...     NaN       대동공업             특수 목적용 기계 제조업
26  000500    2399     54  ...     NaN       가온전선             절연선 및 케이블 제조업
27  000520     294     21  ...     NaN       삼일제약                   의약품 제조업
28  000540   10718    237  ...     NaN       흥국화재                       보험업
29  000590     343     52  ...     NaN      CS홀딩스                    기타 금융업
30  000640    2003    142  ...     NaN   동아쏘시오홀딩스                    기타 금융업
31  000650      71    -19  ...     NaN       천일고속                 육상 여객 운송업
32  000660   86065  19467  ...     NaN     SK하이닉스                   반도체 제조업
33  000670    7139    122  ...     NaN         영풍               1차 비철금속 제조업
34  000680     904    -39  ...     NaN     LS네트웍스                 상품 종합 도매업
35  000700     779      2  ...     NaN      유수홀딩스       회사 본부 및 경영 컨설팅 서비스업
36  000720   45442   1539  ...     NaN       현대건설                    토목 건설업
37  000760     110      1  ...     NaN       이화산업                 기타 전문 도매업
38  000810   61159   3858  ...     NaN   삼성화재해상보험                       보험업
39  000850     418      6  ...     NaN       화천기공             특수 목적용 기계 제조업
40  000860     826     28  ...     NaN     강남제비스코               기타 화학제품 제조업
41  000880  110041   5013  ...     NaN         한화               기타 화학제품 제조업
42  000890     196      8  ...     NaN       보해양조                 알코올음료 제조업
43  000910     434     22  ...     NaN        유니온  시멘트, 석회, 플라스터 및 그 제품 제조업
44  000950     244    -42  ...     NaN         전방              방적 및 가공사 제조업
45  000970    1128     25  ...     NaN    한국주철관공업                 1차 철강 제조업
46  000990    2417    771  ...     NaN      DB하이텍                   반도체 제조업
47  001000       9     -5  ...     NaN       신라섬유         가전제품 및 정보통신장비 소매업
48  001020    2024    132  ...     NaN     페이퍼코리아           펄프, 종이 및 판지 제조업
49  001040   77940   3588  ...     NaN         CJ                    기타 금융업

[50 rows x 19 columns]

In [ ]:
df = df.dropna(axis=1,how='all')

In [ ]:
df

      종목코드     매출액   영업이익  ... PBR(배)        회사명                        업종
0   000020     698     62  ...   1.44       동화약품                   의약품 제조업
1   000040     312      8  ...   1.45      KR모터스            그외 기타 운송장비 제조업
2   000050     862     33  ...   0.43         경방                    종합 소매업
3   000060   27111   1462  ...   0.54      메리츠화재                       보험업
4   000070    5795    337  ...   0.31      삼양홀딩스                    기타 금융업
5   000080    5816    541  ...   2.88      하이트진로                 알코올음료 제조업
6   000100    4155    357  ...   1.76       유한양행                   의약품 제조업
7   000120   26500    839  ...   0.94     CJ대한통운                 도로 화물 운송업
8   000140    5797    575  ...   1.03   하이트진로홀딩스                    기타 금융업
9   000150   42092     79  ...   0.43         두산       회사 본부 및 경영 컨설팅 서비스업
10  000180     423     16  ...   0.18     성창기업지주       회사 본부 및 경영 컨설팅 서비스업
11  000210   25477   3071  ...   0.51       대림산업                    토목 건설업
12  000220     247     17  ...   1.08       유유제약                   의약품 제조업
13  000230    1473     99  ...   0.77      일동홀딩스                   의약품 제조업
14  000240    1757     99  ...   0.36  한국테크놀로지그룹                    기타 금융업
15  000250     443     37  ...   4.91      삼천당제약                   의약품 제조업
16  000270  113688   1452  ...   0.44      기아자동차         자동차용 엔진 및 자동차 제조업
17  000300    1072     39  ...   0.76      대유플러스            통신 및 방송 장비 제조업
18  000320    2197     87  ...   0.26      노루홀딩스                    기타 금융업
19  000370   19393    388  ...   0.16     한화손해보험                       보험업
20  000390    1438     57  ...   0.38    삼화페인트공업               기타 화학제품 제조업
21  000400    9114    350  ...   0.49     롯데손해보험                       보험업
22  000430    1658   -121  ...   0.41       대원강업             자동차 신품 부품 제조업
23  000440     127      2  ...   0.92     중앙에너비스                 기타 전문 도매업
24  000480    1592    -18  ...   0.38       조선내화          내화, 비내화 요업제품 제조업
25  000490    2569    265  ...   0.38       대동공업             특수 목적용 기계 제조업
26  000500    2399     54  ...   0.24       가온전선             절연선 및 케이블 제조업
27  000520     294     21  ...   1.82       삼일제약                   의약품 제조업
28  000540   10718    237  ...    0.2       흥국화재                       보험업
29  000590     343     52  ...    0.3      CS홀딩스                    기타 금융업
30  000640    2003    142  ...   0.77   동아쏘시오홀딩스                    기타 금융업
31  000650      71    -19  ...   1.87       천일고속                 육상 여객 운송업
32  000660   86065  19467  ...   1.18     SK하이닉스                   반도체 제조업
33  000670    7139    122  ...   0.24         영풍               1차 비철금속 제조업
34  000680     904    -39  ...    0.3     LS네트웍스                 상품 종합 도매업
35  000700     779      2  ...   0.65      유수홀딩스       회사 본부 및 경영 컨설팅 서비스업
36  000720   45442   1539  ...   0.55       현대건설                    토목 건설업
37  000760     110      1  ...    0.4       이화산업                 기타 전문 도매업
38  000810   61159   3858  ...   0.51   삼성화재해상보험                       보험업
39  000850     418      6  ...   0.23       화천기공             특수 목적용 기계 제조업
40  000860     826     28  ...   0.17     강남제비스코               기타 화학제품 제조업
41  000880  110041   5013  ...   0.43         한화               기타 화학제품 제조업
42  000890     196      8  ...   1.19       보해양조                 알코올음료 제조업
43  000910     434     22  ...   0.94        유니온  시멘트, 석회, 플라스터 및 그 제품 제조업
44  000950     244    -42  ...    0.3         전방              방적 및 가공사 제조업
45  000970    1128     25  ...    0.7    한국주철관공업                 1차 철강 제조업
46  000990    2417    771  ...    1.7      DB하이텍                   반도체 제조업
47  001000       9     -5  ...    4.1       신라섬유         가전제품 및 정보통신장비 소매업
48  001020    2024    132  ...   1.52     페이퍼코리아           펄프, 종이 및 판지 제조업
49  001040   77940   3588  ...   0.61         CJ                    기타 금융업

[50 rows x 16 columns]

In [ ]:
df.isnull().sum()

종목코드         0
매출액          0
영업이익         0
당기순이익        0
영업이익률        0
순이익률         0
ROE(지배주주)    1
부채비율         0
당좌비율         5
유보율          0
EPS(원)       0
PER(배)       1
BPS(원)       0
PBR(배)       0
회사명          0
업종           0
dtype: int64

In [ ]:
df.dtypes

종목코드         object
매출액          object
영업이익         object
당기순이익        object
영업이익률        object
순이익률         object
ROE(지배주주)    object
부채비율         object
당좌비율         object
유보율          object
EPS(원)       object
PER(배)       object
BPS(원)       object
PBR(배)       object
회사명          object
업종           object
dtype: object

In [ ]:
cols = df.columns[1:-2]

In [ ]:
cols

Index(['매출액', '영업이익', '당기순이익', '영업이익률', '순이익률', 'ROE(지배주주)', '부채비율', '당좌비율',
       '유보율', 'EPS(원)', 'PER(배)', 'BPS(원)', 'PBR(배)'],
      dtype='object')

In [ ]:
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [ ]:
df

      종목코드       매출액     영업이익  ...  PBR(배)        회사명                        업종
0   000020     698.0     62.0  ...    1.44       동화약품                   의약품 제조업
1   000040     312.0      8.0  ...    1.45      KR모터스            그외 기타 운송장비 제조업
2   000050     862.0     33.0  ...    0.43         경방                    종합 소매업
3   000060   27111.0   1462.0  ...    0.54      메리츠화재                       보험업
4   000070    5795.0    337.0  ...    0.31      삼양홀딩스                    기타 금융업
5   000080    5816.0    541.0  ...    2.88      하이트진로                 알코올음료 제조업
6   000100    4155.0    357.0  ...    1.76       유한양행                   의약품 제조업
7   000120   26500.0    839.0  ...    0.94     CJ대한통운                 도로 화물 운송업
8   000140    5797.0    575.0  ...    1.03   하이트진로홀딩스                    기타 금융업
9   000150   42092.0     79.0  ...    0.43         두산       회사 본부 및 경영 컨설팅 서비스업
10  000180     423.0     16.0  ...    0.18     성창기업지주       회사 본부 및 경영 컨설팅 서비스업
11  000210   25477.0   3071.0  ...    0.51       대림산업                    토목 건설업
12  000220     247.0     17.0  ...    1.08       유유제약                   의약품 제조업
13  000230    1473.0     99.0  ...    0.77      일동홀딩스                   의약품 제조업
14  000240    1757.0     99.0  ...    0.36  한국테크놀로지그룹                    기타 금융업
15  000250     443.0     37.0  ...    4.91      삼천당제약                   의약품 제조업
16  000270  113688.0   1452.0  ...    0.44      기아자동차         자동차용 엔진 및 자동차 제조업
17  000300    1072.0     39.0  ...    0.76      대유플러스            통신 및 방송 장비 제조업
18  000320    2197.0     87.0  ...    0.26      노루홀딩스                    기타 금융업
19  000370   19393.0    388.0  ...    0.16     한화손해보험                       보험업
20  000390    1438.0     57.0  ...    0.38    삼화페인트공업               기타 화학제품 제조업
21  000400    9114.0    350.0  ...    0.49     롯데손해보험                       보험업
22  000430    1658.0   -121.0  ...    0.41       대원강업             자동차 신품 부품 제조업
23  000440     127.0      2.0  ...    0.92     중앙에너비스                 기타 전문 도매업
24  000480    1592.0    -18.0  ...    0.38       조선내화          내화, 비내화 요업제품 제조업
25  000490    2569.0    265.0  ...    0.38       대동공업             특수 목적용 기계 제조업
26  000500    2399.0     54.0  ...    0.24       가온전선             절연선 및 케이블 제조업
27  000520     294.0     21.0  ...    1.82       삼일제약                   의약품 제조업
28  000540   10718.0    237.0  ...    0.20       흥국화재                       보험업
29  000590     343.0     52.0  ...    0.30      CS홀딩스                    기타 금융업
30  000640    2003.0    142.0  ...    0.77   동아쏘시오홀딩스                    기타 금융업
31  000650      71.0    -19.0  ...    1.87       천일고속                 육상 여객 운송업
32  000660   86065.0  19467.0  ...    1.18     SK하이닉스                   반도체 제조업
33  000670    7139.0    122.0  ...    0.24         영풍               1차 비철금속 제조업
34  000680     904.0    -39.0  ...    0.30     LS네트웍스                 상품 종합 도매업
35  000700     779.0      2.0  ...    0.65      유수홀딩스       회사 본부 및 경영 컨설팅 서비스업
36  000720   45442.0   1539.0  ...    0.55       현대건설                    토목 건설업
37  000760     110.0      1.0  ...    0.40       이화산업                 기타 전문 도매업
38  000810   61159.0   3858.0  ...    0.51   삼성화재해상보험                       보험업
39  000850     418.0      6.0  ...    0.23       화천기공             특수 목적용 기계 제조업
40  000860     826.0     28.0  ...    0.17     강남제비스코               기타 화학제품 제조업
41  000880  110041.0   5013.0  ...    0.43         한화               기타 화학제품 제조업
42  000890     196.0      8.0  ...    1.19       보해양조                 알코올음료 제조업
43  000910     434.0     22.0  ...    0.94        유니온  시멘트, 석회, 플라스터 및 그 제품 제조업
44  000950     244.0    -42.0  ...    0.30         전방              방적 및 가공사 제조업
45  000970    1128.0     25.0  ...    0.70    한국주철관공업                 1차 철강 제조업
46  000990    2417.0    771.0  ...    1.70      DB하이텍                   반도체 제조업
47  001000       9.0     -5.0  ...    4.10       신라섬유         가전제품 및 정보통신장비 소매업
48  001020    2024.0    132.0  ...    1.52     페이퍼코리아           펄프, 종이 및 판지 제조업
49  001040   77940.0   3588.0  ...    0.61         CJ                    기타 금융업

[50 rows x 16 columns]

In [ ]:
df.dtypes

종목코드          object
매출액          float64
영업이익         float64
당기순이익        float64
영업이익률        float64
순이익률         float64
ROE(지배주주)    float64
부채비율         float64
당좌비율         float64
유보율          float64
EPS(원)       float64
PER(배)       float64
BPS(원)       float64
PBR(배)       float64
회사명           object
업종            object
dtype: object

In [ ]:
df = df.dropna()

In [ ]:
df

      종목코드       매출액     영업이익  ...  PBR(배)        회사명                        업종
0   000020     698.0     62.0  ...    1.44       동화약품                   의약품 제조업
1   000040     312.0      8.0  ...    1.45      KR모터스            그외 기타 운송장비 제조업
2   000050     862.0     33.0  ...    0.43         경방                    종합 소매업
4   000070    5795.0    337.0  ...    0.31      삼양홀딩스                    기타 금융업
5   000080    5816.0    541.0  ...    2.88      하이트진로                 알코올음료 제조업
6   000100    4155.0    357.0  ...    1.76       유한양행                   의약품 제조업
7   000120   26500.0    839.0  ...    0.94     CJ대한통운                 도로 화물 운송업
8   000140    5797.0    575.0  ...    1.03   하이트진로홀딩스                    기타 금융업
9   000150   42092.0     79.0  ...    0.43         두산       회사 본부 및 경영 컨설팅 서비스업
10  000180     423.0     16.0  ...    0.18     성창기업지주       회사 본부 및 경영 컨설팅 서비스업
11  000210   25477.0   3071.0  ...    0.51       대림산업                    토목 건설업
12  000220     247.0     17.0  ...    1.08       유유제약                   의약품 제조업
13  000230    1473.0     99.0  ...    0.77      일동홀딩스                   의약품 제조업
14  000240    1757.0     99.0  ...    0.36  한국테크놀로지그룹                    기타 금융업
15  000250     443.0     37.0  ...    4.91      삼천당제약                   의약품 제조업
16  000270  113688.0   1452.0  ...    0.44      기아자동차         자동차용 엔진 및 자동차 제조업
17  000300    1072.0     39.0  ...    0.76      대유플러스            통신 및 방송 장비 제조업
18  000320    2197.0     87.0  ...    0.26      노루홀딩스                    기타 금융업
20  000390    1438.0     57.0  ...    0.38    삼화페인트공업               기타 화학제품 제조업
22  000430    1658.0   -121.0  ...    0.41       대원강업             자동차 신품 부품 제조업
24  000480    1592.0    -18.0  ...    0.38       조선내화          내화, 비내화 요업제품 제조업
25  000490    2569.0    265.0  ...    0.38       대동공업             특수 목적용 기계 제조업
26  000500    2399.0     54.0  ...    0.24       가온전선             절연선 및 케이블 제조업
27  000520     294.0     21.0  ...    1.82       삼일제약                   의약품 제조업
29  000590     343.0     52.0  ...    0.30      CS홀딩스                    기타 금융업
30  000640    2003.0    142.0  ...    0.77   동아쏘시오홀딩스                    기타 금융업
31  000650      71.0    -19.0  ...    1.87       천일고속                 육상 여객 운송업
32  000660   86065.0  19467.0  ...    1.18     SK하이닉스                   반도체 제조업
33  000670    7139.0    122.0  ...    0.24         영풍               1차 비철금속 제조업
34  000680     904.0    -39.0  ...    0.30     LS네트웍스                 상품 종합 도매업
35  000700     779.0      2.0  ...    0.65      유수홀딩스       회사 본부 및 경영 컨설팅 서비스업
36  000720   45442.0   1539.0  ...    0.55       현대건설                    토목 건설업
37  000760     110.0      1.0  ...    0.40       이화산업                 기타 전문 도매업
39  000850     418.0      6.0  ...    0.23       화천기공             특수 목적용 기계 제조업
40  000860     826.0     28.0  ...    0.17     강남제비스코               기타 화학제품 제조업
41  000880  110041.0   5013.0  ...    0.43         한화               기타 화학제품 제조업
43  000910     434.0     22.0  ...    0.94        유니온  시멘트, 석회, 플라스터 및 그 제품 제조업
44  000950     244.0    -42.0  ...    0.30         전방              방적 및 가공사 제조업
45  000970    1128.0     25.0  ...    0.70    한국주철관공업                 1차 철강 제조업
46  000990    2417.0    771.0  ...    1.70      DB하이텍                   반도체 제조업
47  001000       9.0     -5.0  ...    4.10       신라섬유         가전제품 및 정보통신장비 소매업
48  001020    2024.0    132.0  ...    1.52     페이퍼코리아           펄프, 종이 및 판지 제조업
49  001040   77940.0   3588.0  ...    0.61         CJ                    기타 금융업

[43 rows x 16 columns]

In [ ]:
len(df)

43

In [ ]:
from sklearn.cluster import KMeans
X = df.iloc[:,1:-2].values
kmeans = KMeans(n_clusters=5, random_state=0).fit(X)

In [ ]:
kmeans.labels_

array([0, 0, 0, 2, 0, 0, 2, 0, 4, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0,
       4, 0, 2, 2, 0, 3, 1, 0, 0, 4, 0, 2, 4, 3, 0, 4, 0, 0, 0, 0, 2],
      dtype=int32)

In [ ]:
df['label'] = kmeans.labels_

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df

      종목코드       매출액     영업이익  ...        회사명                        업종  label
0   000020     698.0     62.0  ...       동화약품                   의약품 제조업      0
1   000040     312.0      8.0  ...      KR모터스            그외 기타 운송장비 제조업      0
2   000050     862.0     33.0  ...         경방                    종합 소매업      0
4   000070    5795.0    337.0  ...      삼양홀딩스                    기타 금융업      2
5   000080    5816.0    541.0  ...      하이트진로                 알코올음료 제조업      0
6   000100    4155.0    357.0  ...       유한양행                   의약품 제조업      0
7   000120   26500.0    839.0  ...     CJ대한통운                 도로 화물 운송업      2
8   000140    5797.0    575.0  ...   하이트진로홀딩스                    기타 금융업      0
9   000150   42092.0     79.0  ...         두산       회사 본부 및 경영 컨설팅 서비스업      4
10  000180     423.0     16.0  ...     성창기업지주       회사 본부 및 경영 컨설팅 서비스업      0
11  000210   25477.0   3071.0  ...       대림산업                    토목 건설업      2
12  000220     247.0     17.0  ...       유유제약                   의약품 제조업      0
13  000230    1473.0     99.0  ...      일동홀딩스                   의약품 제조업      0
14  000240    1757.0     99.0  ...  한국테크놀로지그룹                    기타 금융업      0
15  000250     443.0     37.0  ...      삼천당제약                   의약품 제조업      0
16  000270  113688.0   1452.0  ...      기아자동차         자동차용 엔진 및 자동차 제조업      3
17  000300    1072.0     39.0  ...      대유플러스            통신 및 방송 장비 제조업      0
18  000320    2197.0     87.0  ...      노루홀딩스                    기타 금융업      0
20  000390    1438.0     57.0  ...    삼화페인트공업               기타 화학제품 제조업      0
22  000430    1658.0   -121.0  ...       대원강업             자동차 신품 부품 제조업      0
24  000480    1592.0    -18.0  ...       조선내화          내화, 비내화 요업제품 제조업      2
25  000490    2569.0    265.0  ...       대동공업             특수 목적용 기계 제조업      0
26  000500    2399.0     54.0  ...       가온전선             절연선 및 케이블 제조업      4
27  000520     294.0     21.0  ...       삼일제약                   의약품 제조업      0
29  000590     343.0     52.0  ...      CS홀딩스                    기타 금융업      2
30  000640    2003.0    142.0  ...   동아쏘시오홀딩스                    기타 금융업      2
31  000650      71.0    -19.0  ...       천일고속                 육상 여객 운송업      0
32  000660   86065.0  19467.0  ...     SK하이닉스                   반도체 제조업      3
33  000670    7139.0    122.0  ...         영풍               1차 비철금속 제조업      1
34  000680     904.0    -39.0  ...     LS네트웍스                 상품 종합 도매업      0
35  000700     779.0      2.0  ...      유수홀딩스       회사 본부 및 경영 컨설팅 서비스업      0
36  000720   45442.0   1539.0  ...       현대건설                    토목 건설업      4
37  000760     110.0      1.0  ...       이화산업                 기타 전문 도매업      0
39  000850     418.0      6.0  ...       화천기공             특수 목적용 기계 제조업      2
40  000860     826.0     28.0  ...     강남제비스코               기타 화학제품 제조업      4
41  000880  110041.0   5013.0  ...         한화               기타 화학제품 제조업      3
43  000910     434.0     22.0  ...        유니온  시멘트, 석회, 플라스터 및 그 제품 제조업      0
44  000950     244.0    -42.0  ...         전방              방적 및 가공사 제조업      4
45  000970    1128.0     25.0  ...    한국주철관공업                 1차 철강 제조업      0
46  000990    2417.0    771.0  ...      DB하이텍                   반도체 제조업      0
47  001000       9.0     -5.0  ...       신라섬유         가전제품 및 정보통신장비 소매업      0
48  001020    2024.0    132.0  ...     페이퍼코리아           펄프, 종이 및 판지 제조업      0
49  001040   77940.0   3588.0  ...         CJ                    기타 금융업      2

[43 rows x 17 columns]

In [ ]:
df.label.value_counts()

0    26
2     8
4     5
3     3
1     1
Name: label, dtype: int64

In [ ]:
df[df.label==2]

      종목코드      매출액    영업이익   당기순이익  ...  PBR(배)       회사명                업종  label
4   000070   5795.0   337.0   281.0  ...    0.31     삼양홀딩스            기타 금융업      2
7   000120  26500.0   839.0   362.0  ...    0.94    CJ대한통운         도로 화물 운송업      2
11  000210  25477.0  3071.0  1885.0  ...    0.51      대림산업            토목 건설업      2
24  000480   1592.0   -18.0   350.0  ...    0.38      조선내화  내화, 비내화 요업제품 제조업      2
29  000590    343.0    52.0    38.0  ...    0.30     CS홀딩스            기타 금융업      2
30  000640   2003.0   142.0    64.0  ...    0.77  동아쏘시오홀딩스            기타 금융업      2
39  000850    418.0     6.0    41.0  ...    0.23      화천기공     특수 목적용 기계 제조업      2
49  001040  77940.0  3588.0   552.0  ...    0.61        CJ            기타 금융업      2

[8 rows x 17 columns]

In [ ]:
df[df.label==4]

      종목코드      매출액    영업이익   당기순이익  ...  PBR(배)     회사명                   업종  label
9   000150  42092.0    79.0 -2372.0  ...    0.43      두산  회사 본부 및 경영 컨설팅 서비스업      4
26  000500   2399.0    54.0    56.0  ...    0.24    가온전선        절연선 및 케이블 제조업      4
36  000720  45442.0  1539.0   694.0  ...    0.55    현대건설               토목 건설업      4
40  000860    826.0    28.0    75.0  ...    0.17  강남제비스코          기타 화학제품 제조업      4
44  000950    244.0   -42.0   -45.0  ...    0.30      전방         방적 및 가공사 제조업      4

[5 rows x 17 columns]